import type {Metadata} from 'next';
import Image from 'next/image';
import {PublicShell} from '@/components/PublicShell';
import {FoundingCtaLink} from '@/components/FoundingCtaLink';

export const metadata:Metadata={title:'The Founding Story',description:'The story behind Ramah Digital and why its one Founding Era will remain a permanent part of its history.',alternates:{canonical:'/story'}};

const chapters=[
 {number:'02',title:'Why the Founding Era Exists',body:<><p>Every meaningful company has a beginning.</p><p className="story-cadence">Not the day it becomes famous.<br/>Not the day millions hear its name.</p><p>Its true beginning is the moment when a small group of people decide that an idea is worth believing in before the rest of the world arrives.</p><p>That moment is the Founding Era.</p><p>This is the chapter where Ramah is still being written.</p><p>The people who join during this period are not simply early customers. They become part of the permanent history of the platform. They choose to support a vision before it has reached its full scale, knowing that every suggestion, every booking, every conversation, and every act of encouragement helps shape what Ramah will become for years to come.</p><p>The Founding Era is intentionally limited because beginnings only happen once.</p></>},
 {number:'03',title:"A Permanent Place in Ramah's History",body:<><p>When the Founding Era closes, it closes forever.</p><p>No additional Global Founding memberships will be created.</p><p>The Founder Numbers assigned during this period become permanent historical records within Ramah.</p><p>Every Global Founding Traveler and every Global Founding Host will forever be recognised as someone who believed in the mission before it became established.</p><div className="story-vow"><p>Your Founder identity is not temporary.</p><p>It is not something that expires.</p><p>It is not reset when you change devices, upgrade your membership, or sign in through the mobile application.</p></div><p>It becomes part of your Ramah identity permanently.</p><p>Wherever your Ramah journey continues, your Founder story continues with it.</p></>},
 {number:'04',title:'Built Together',body:<><p>The future of Ramah will not be written by developers alone.</p><p>It will be shaped by travelers who explore new places.</p><p>By hosts who open their doors with genuine hospitality.</p><p>By people who report problems, suggest improvements, celebrate successes, and help us build a platform that truly serves its community.</p><p>The Founding Era is an invitation to become part of that journey.</p><p>Not because founders are more important than future members, but because someone must take the first step.</p><p>Every great community remembers those first steps.</p></>},
 {number:'05',title:'Trust Before Scale',body:<><p>Many companies pursue rapid growth before earning lasting trust.</p><p>We believe the opposite approach creates stronger foundations.</p><p className="story-cadence">Before millions of users…<br/>Before international expansion…<br/>Before new products and services…</p><p>There must be a community built on honesty, transparency, and shared purpose.</p><p>That is why the Founding Era focuses on people rather than numbers.</p><p>We would rather build something meaningful with a few hundred committed founders than something enormous without a clear purpose.</p><p className="story-axiom">Growth will come.<br/><strong>Character must come first.</strong></p></>},
 {number:'06',title:'More Than Membership',body:<><p>Joining the Founding Era is not simply purchasing a membership.</p><p>It is becoming part of a permanent chapter in Ramah&apos;s history.</p><ul className="story-symbols"><li>Your Founder Number.</li><li>Your Founder Badge.</li><li>Your place within the Founder Hall.</li><li>Your recognition as one of the people who helped shape Ramah before its public launch.</li></ul><p>These are lasting symbols of participation in the beginning of a journey that we hope will connect millions of travelers and hospitality partners across Africa and beyond.</p></>},
] as const;

export default function Page(){return <PublicShell>
 <section className="story-hero"><Image src="/images/founding-hero.png" fill sizes="100vw" priority alt="Travelers arriving at an African highland lodge at sunrise"/><div className="story-hero-shade"/><div className="story-hero-copy"><span className="eyebrow light">The Story · Ramah Digital</span><h1>Before There<br/>Was <em>Ramah.</em></h1><p>Every journey begins long before the first booking.</p></div><div className="story-hero-foot"><span>THE FOUNDING RECORD</span><span>CHAPTER ONE · 2026</span></div></section>

 <section className="story-opening"><aside><span>01</span><small>THE ORIGIN</small></aside><div className="story-opening-title"><span className="eyebrow">The people behind every journey</span><h2>Long before arrival, someone is preparing a welcome.</h2></div><div className="story-copy"><p>Long before a traveler arrives at a destination, there is someone waiting to welcome them. Long before a hotel opens its doors each morning, there are people preparing rooms, making beds, cooking meals, sharing stories, and preserving the places that make travel meaningful.</p><p>Yet for too long, many of those stories have remained invisible.</p><p>Across Africa and the Global South, extraordinary destinations, remarkable accommodations, and unforgettable experiences have often existed beyond the spotlight of the world&apos;s largest travel platforms. Travelers frequently struggle to discover authentic places, while local hospitality businesses work tirelessly without receiving the visibility, trust, and opportunities they deserve.</p></div></section>

 <section className="story-belief"><span className="eyebrow light">The belief that started it</span><blockquote>Travel should create opportunity, build trust, celebrate culture, and leave every place better than it was found.</blockquote><div><p>We believe technology should strengthen human connections—not replace them. It should help travelers discover with confidence, help accommodation partners grow sustainably, and help local communities benefit from the journeys that pass through them.</p><p>That belief became <strong>Ramah Digital.</strong></p><p>Not simply another travel platform, but the beginning of a travel ecosystem designed for the realities, ambitions, and future of Africa and the wider Global South.</p></div></section>

 <section className="story-image-break"><Image src="/images/founding-community.png" fill sizes="100vw" alt="Travelers and hospitality hosts sharing stories in a sunlit courtyard"/><div><span className="eyebrow light">Human before digital</span><p>Every place has a story.<br/>Every welcome has a name.</p></div></section>

 <div className="story-chapters">{chapters.map((chapter,index)=><section className={`story-chapter${index%2?' reverse':''}`} key={chapter.number}><aside><span>{chapter.number}</span><small>THE FOUNDING STORY</small></aside><div className="story-chapter-title"><h2>{chapter.title}</h2></div><div className="story-copy">{chapter.body}</div></section>)}</div>

 <section className="story-finale"><span className="eyebrow light">07 · The Journey Starts Here</span><h2>“I was there<br/>when it all <em>began.</em>”</h2><div className="story-finale-copy"><p>Years from now, thousands—perhaps millions—of people may travel through Ramah.</p><p>Most will discover a mature platform with established communities, trusted hosts, and thriving destinations.</p><p>Only a small number will be able to say those words.</p><p>Those people will always have a place in Ramah&apos;s story.</p><p>This is your invitation to become one of them.</p><strong>Welcome to the Ramah Digital Founding Era.</strong></div><div className="actions"><FoundingCtaLink className="button light" kind="traveler" tier="explore"/><FoundingCtaLink className="button outline-light" kind="host" tier="community"/></div></section>
 </PublicShell>}
