"use server";
import {createClient} from '@/lib/supabase/server';
import {redirect} from 'next/navigation';
import {revalidatePath} from 'next/cache';

const text=(f:FormData,k:string)=>String(f.get(k)??'').trim();
const list=(f:FormData,k:string)=>f.getAll(k).map(String).flatMap(v=>v.split(/[\n\r,;]+/)).map(v=>v.trim()).filter(Boolean);
const number=(f:FormData,k:string,min=0)=>{const value=Number(text(f,k));if(!Number.isFinite(value)||value<min)throw new Error(`${k} is invalid`);return value};
async function context(){const sb=await createClient();const {data:{user}}=await sb.auth.getUser();if(!user)redirect('/auth/sign-in');return {sb,user};}
function mediaUrls(form:FormData,key:string,bucket:string,userId:string){
  const base=(process.env.NEXT_PUBLIC_SUPABASE_URL??'').replace(/\/$/,'');
  const prefix=`${base}/storage/v1/object/public/${bucket}/${userId}/`;
  return form.getAll(key).map(String).map(value=>value.trim()).filter(Boolean).map(value=>{
    if(!value.startsWith(prefix))throw new Error(`Invalid ${bucket} storage reference`);
    return value;
  });
}
function fail(error:unknown){
  if(error&&typeof error==='object'&&'digest' in error&&String(error.digest).startsWith('NEXT_REDIRECT'))throw error;
  return `/portal/onboarding?error=${encodeURIComponent(error instanceof Error?error.message:'Unable to save onboarding information')}`;
}

export async function saveFutureProfile(form:FormData){try{const {sb,user}=await context();const avatar=mediaUrls(form,'avatarUrl','avatars',user.id)[0],cover=mediaUrls(form,'profileCoverUrl','covers',user.id)[0];const values:Record<string,unknown>={full_name:text(form,'fullName'),phone:text(form,'phone')||null,bio:text(form,'bio')||null,country:text(form,'country')||null,location:text(form,'city')||null,spoken_languages:list(form,'languages'),travel_interests:list(form,'interests'),preferred_travel_styles:list(form,'travelStyles')};if(avatar)values.avatar_url=avatar;if(cover)values.cover_url=cover;const {error}=await sb.from('profiles').update(values).eq('id',user.id);if(error)throw error;revalidatePath('/portal/onboarding');redirect('/portal/onboarding?notice=Future profile saved');}catch(e){redirect(fail(e))}}

export async function saveProperty(form:FormData){try{const {sb,user}=await context();const existingId=text(form,'propertyId'),cover=mediaUrls(form,'propertyCoverUrl','hotel-images',user.id)[0],uploadedGallery=mediaUrls(form,'galleryUrls','hotel-images',user.id);const propertyName=text(form,'propertyName'),propertyType=text(form,'propertyType'),location=text(form,'location'),country=text(form,'propertyCountry');if(propertyName.length<2||!propertyType||!location||!country)throw new Error('Property name, type, city and country are required');const values:Record<string,unknown>={owner_id:user.id,name:propertyName,location,country,type:propertyType,category:list(form,'categories').slice(0,3).join(', '),property_categories:list(form,'categories').slice(0,3),description:text(form,'propertyDescription'),amenities:list(form,'amenities'),highlights:list(form,'highlights'),house_rules:text(form,'houseRules')||null,check_in_time:text(form,'checkIn')||null,check_out_time:text(form,'checkOut')||null,cancellation_policy_type:text(form,'cancellationPolicyType')||null,cancellation_policy_text:text(form,'cancellationPolicy')||null,children_policy:text(form,'childrenPolicy')||null,pets_policy:text(form,'petsPolicy')||null,smoking_policy:text(form,'smokingPolicy')||null,extra_rules:text(form,'policies')||null,status:'draft',operational_status:'draft',verified:false};if(cover){values.cover_url=cover;values.cover_photo_url=cover}let propertyId=existingId;if(existingId){const {data:existing}=await sb.from('hotels').select('id,gallery_urls').eq('id',existingId).eq('owner_id',user.id).single();if(!existing)throw new Error('Property ownership could not be verified');if(uploadedGallery.length)values.gallery_urls=[...new Set([...(existing.gallery_urls??[]),...uploadedGallery])];delete values.owner_id;const {error}=await sb.from('hotels').update(values).eq('id',existingId).eq('owner_id',user.id);if(error)throw error}else{const {data:alreadyOwned}=await sb.from('hotels').select('id').eq('owner_id',user.id).limit(1).maybeSingle();if(alreadyOwned)throw new Error('This host account already has a property. Edit the owned property instead.');values.gallery_urls=uploadedGallery;const {data,error}=await sb.from('hotels').insert(values).select('id').single();if(error)throw error;propertyId=data.id}const {error:profileError}=await sb.from('profiles').update({business_name:propertyName,property_type:propertyType,country,location}).eq('id',user.id);if(profileError)throw profileError;revalidatePath('/portal/onboarding');redirect(`/portal/onboarding?property=${propertyId}&notice=Private property draft saved`);}catch(e){redirect(fail(e))}}

export async function addRoom(form:FormData){try{const {sb,user}=await context();const propertyId=text(form,'propertyId');const {data:property}=await sb.from('hotels').select('id').eq('id',propertyId).eq('owner_id',user.id).maybeSingle();if(!property)throw new Error('Property ownership could not be verified');const image=mediaUrls(form,'roomImageUrl','room-images',user.id)[0]??null,price=number(form,'price');const {error}=await sb.from('rooms').insert({hotel_id:propertyId,name:text(form,'roomName'),description:text(form,'roomDescription')||null,room_type:text(form,'roomType'),price,base_price:price,currency:text(form,'currency')||'USD',capacity:number(form,'occupancy',1),bed_count:number(form,'beds',1),bathroom_count:number(form,'bathrooms',0),available_quantity:number(form,'quantity',1),amenities:list(form,'roomAmenities'),image,image_url:image,status:'draft'});if(error)throw error;revalidatePath('/portal/onboarding');redirect(`/portal/onboarding?property=${propertyId}&notice=Room added to launch inventory`);}catch(e){redirect(fail(e))}}

export async function saveLaunchDeal(form:FormData){try{const {sb,user}=await context();const propertyId=text(form,'propertyId'),duration=number(form,'durationDays',1);const {data:property}=await sb.from('hotels').select('id').eq('id',propertyId).eq('owner_id',user.id).maybeSingle();if(!property)throw new Error('Property ownership could not be verified');const start=new Date();start.setUTCFullYear(start.getUTCFullYear()+20);const end=new Date(start);end.setUTCDate(end.getUTCDate()+duration);const {error}=await sb.from('hotel_deals').insert({hotel_id:propertyId,room_id:null,host_id:user.id,title:text(form,'dealTitle')||'Launch Deal',discount_percent:number(form,'discount',1),applies_to:'all_rooms',start_date:start.toISOString().slice(0,10),end_date:end.toISOString().slice(0,10),status:'inactive',note:text(form,'dealDescription')||null,launch_duration_days:duration,launch_activation_status:'configured'});if(error)throw error;revalidatePath('/portal/onboarding');redirect(`/portal/onboarding?property=${propertyId}&notice=Launch Deal configured and paused`);}catch(e){redirect(fail(e))}}

export async function uploadShowcaseVideo(form:FormData){try{const {sb,user}=await context();const propertyId=text(form,'propertyId'),videoUrl=mediaUrls(form,'showcaseVideoUrl','videos',user.id)[0];if(!videoUrl)throw new Error('Choose a property showcase video');const {data:property}=await sb.from('hotels').select('id').eq('id',propertyId).eq('owner_id',user.id).maybeSingle();if(!property)throw new Error('Property ownership could not be verified');const {error}=await sb.from('hotel_videos').insert({content_type:'hotel',creator_type:'hotel',creator_profile_id:user.id,hotel_id:propertyId,owner_id:user.id,user_id:user.id,title:text(form,'videoTitle')||'Property showcase',caption:text(form,'videoDescription')||null,video_url:videoUrl,status:'hidden',moderation_status:'pending_review',is_review:false});if(error)throw error;revalidatePath('/portal/onboarding');redirect(`/portal/onboarding?property=${propertyId}&notice=Property showcase stored for launch review`);}catch(e){redirect(fail(e))}}

export async function submitPropertyReadiness(form:FormData){try{const {sb,user}=await context();const propertyId=text(form,'propertyId');const {error}=await sb.from('hotels').update({status:'pending_verification',operational_status:'pending_verification'}).eq('id',propertyId).eq('owner_id',user.id);if(error)throw error;revalidatePath('/portal/onboarding');redirect('/portal/apply?notice=Property submitted for launch-readiness review');}catch(e){redirect(fail(e))}}
