import {createClient} from '@/lib/supabase/server';
import {HOTEL_AMENITIES,LANGUAGES,PROPERTY_CATEGORIES,PROPERTY_TYPES,ROOM_AMENITIES,ROOM_TYPES,TRAVEL_STYLES} from '@/lib/onboarding';
import {DirectUploadForm} from '@/components/DirectUploadForm';
import {addRoom,saveFutureProfile,saveLaunchDeal,saveProperty,submitPropertyReadiness,uploadShowcaseVideo} from './actions';

const Checks=({name,values,selected=[]}:{name:string;values:readonly string[];selected?:string[]})=><div className="choice-grid">{values.map(value=><label key={value}><input type="checkbox" name={name} value={value} defaultChecked={selected.includes(value)}/><span>{value}</span></label>)}</div>;

export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const q=await searchParams,sb=await createClient();
  const {data:{user}}=await sb.auth.getUser();
  const [{data:profile},{data:hotels}]=await Promise.all([sb.from('profiles').select('*').eq('id',user!.id).single(),sb.from('hotels').select('*').eq('owner_id',user!.id).order('created_at').limit(1)]);
  const property=hotels?.[0],propertyId=property?.id;
  const [{data:rooms},{data:deals},{data:videos}]=propertyId?await Promise.all([
    sb.from('rooms').select('id,name,room_type,capacity,price,currency,status,image_url').eq('hotel_id',propertyId),
    sb.from('hotel_deals').select('id,title,discount_percent,launch_duration_days,status').eq('hotel_id',propertyId),
    sb.from('hotel_videos').select('id,title,video_url,status,moderation_status').eq('hotel_id',propertyId).eq('content_type','hotel'),
  ]):[{data:[]},{data:[]},{data:[]}];
  const host=profile?.role==='hotel_partner';
  const profileMedia=[...(profile?.avatar_url?[{url:profile.avatar_url,kind:'image' as const,label:'Current profile photo'}]:[]),...(profile?.cover_url?[{url:profile.cover_url,kind:'image' as const,label:'Current profile cover'}]:[])];
  const propertyMedia=[...(property?.cover_url?[{url:property.cover_url,kind:'image' as const,label:'Current property cover'}]:[]),...(property?.gallery_urls??[]).map((url:string,index:number)=>({url,kind:'image' as const,label:`Gallery image ${index+1}`}))];
  const videoMedia=(videos??[]).filter(v=>v.video_url).map(v=>({url:v.video_url!,kind:'video' as const,label:v.title??'Property showcase'}));

  return <section className="onboarding-page">
    <header className="onboarding-hero"><span className="eyebrow light">Pre-launch provisioning</span><h1>Arrive at launch<br/><em>already ready.</em></h1><p>Your information is written to the same Ramah account and backend the mobile application uses. Launch-only content stays dormant until authorized activation.</p></header>
    {q.error&&<p className="form-error">{q.error}</p>}{q.notice&&<p className="notice">{q.notice}</p>}
    <nav className="onboarding-steps" aria-label="Host onboarding progress"><a href="#profile">01 Profile</a>{host&&<><a href="#property">02 Property type</a><a href="#property-information">03 Information</a><a href="#property-features">04 Amenities</a><a href="#property-policies">05 Policies</a><a href="#rooms">06 Rooms</a><a href="#discover">07 Media</a><a href="#deal">08 Launch Deal</a><a href="#review">09 Review</a></>}</nav>

    <OnboardingSection id="profile" number="01" title="Your future Ramah profile" copy="This becomes your profile across Ramah. Travelers stop here—no video is requested from traveler Founders.">
      <DirectUploadForm action={saveFutureProfile} className="provision-form" initialMedia={profileMedia}>
        <label>Full name<input name="fullName" required defaultValue={profile?.full_name??''}/></label><label>Phone<input name="phone" type="tel" defaultValue={profile?.phone??''}/></label><label>Country<input name="country" defaultValue={profile?.country??''}/></label><label>City<input name="city" defaultValue={profile?.location??''}/></label>
        <label className="wide">Biography<textarea name="bio" defaultValue={profile?.bio??''}/></label>
        <label>Profile photo<input type="file" accept="image/jpeg,image/png,image/webp" data-upload-bucket="avatars" data-upload-output="avatarUrl"/></label>
        <label>Cover photo<input type="file" accept="image/jpeg,image/png,image/webp" data-upload-bucket="covers" data-upload-output="profileCoverUrl"/></label>
        <fieldset className="wide"><legend>Languages</legend><Checks name="languages" values={LANGUAGES} selected={profile?.spoken_languages??[]}/></fieldset>
        <fieldset className="wide"><legend>Interests & travel styles</legend><Checks name="interests" values={TRAVEL_STYLES} selected={profile?.travel_interests??[]}/><Checks name="travelStyles" values={TRAVEL_STYLES} selected={profile?.preferred_travel_styles??[]}/></fieldset>
      </DirectUploadForm>
    </OnboardingSection>

    {host?<>
      <OnboardingSection id="property" number="02" title="Build the property record" copy="The same hotel record the Expo app will open after launch—held in draft and never bookable early.">
        <DirectUploadForm action={saveProperty} className="provision-form" initialMedia={propertyMedia}>
          <input type="hidden" name="propertyId" value={propertyId??''}/><div className="wide stage-label" id="property-information"><b>Property information</b><span>Enter your own property. No marketplace listing is selectable here.</span></div><label>Property type<select name="propertyType" required defaultValue={property?.type??profile?.property_type??''}><option value="">Choose type</option>{PROPERTY_TYPES.map(x=><option value={x} key={x}>{x}</option>)}</select></label><label>Property name<input name="propertyName" required minLength={2} defaultValue={property?.name??profile?.business_name??''} placeholder="e.g. Nile Riverside Lodge"/></label><label>City / location<input name="location" required defaultValue={property?.location??profile?.location??''}/></label><label>Country<input name="propertyCountry" required defaultValue={property?.country??profile?.country??''}/></label>
          <div className="wide stage-label" id="property-features"><b>Property features</b><span>The same categories and amenities used by the Ramah app.</span></div><fieldset className="wide"><legend>Categories (choose up to three)</legend><Checks name="categories" values={PROPERTY_CATEGORIES} selected={property?.property_categories??[]}/></fieldset><fieldset className="wide"><legend>Amenities & accessibility</legend><Checks name="amenities" values={HOTEL_AMENITIES} selected={property?.amenities??[]}/></fieldset>
          <label className="wide">Property description<textarea name="propertyDescription" required defaultValue={property?.description??''}/></label><label className="wide">Highlights and nearby attractions <small>One per line</small><textarea name="highlights" defaultValue={(property?.highlights??[]).join('\n')}/></label><div className="wide stage-label" id="property-policies"><b>Policies</b><span>Set the rules guests will see in the shared Ramah property record.</span></div><label>Check-in time<input name="checkIn" type="time" defaultValue={property?.check_in_time??''}/></label><label>Check-out time<input name="checkOut" type="time" defaultValue={property?.check_out_time??''}/></label><label>Children<select name="childrenPolicy" defaultValue={property?.children_policy??''}><option value="">Not specified</option><option value="allowed">Allowed</option><option value="family_friendly">Family friendly</option><option value="not_allowed">Not allowed</option></select></label><label>Pets<select name="petsPolicy" defaultValue={property?.pets_policy??''}><option value="">Not specified</option><option value="allowed">Allowed</option><option value="ask_first">Ask first</option><option value="not_allowed">Not allowed</option></select></label><label>Smoking<select name="smokingPolicy" defaultValue={property?.smoking_policy??''}><option value="">Not specified</option><option value="not_allowed">Not allowed</option><option value="designated_areas">Designated areas</option><option value="allowed">Allowed</option></select></label><label>Cancellation type<select name="cancellationPolicyType" defaultValue={property?.cancellation_policy_type??''}><option value="">Custom</option><option value="flexible">Flexible</option><option value="moderate">Moderate</option><option value="strict">Strict</option><option value="non_refundable">Non-refundable</option></select></label><label className="wide">House rules<textarea name="houseRules" defaultValue={property?.house_rules??''}/></label><label>Cancellation details<textarea name="cancellationPolicy" defaultValue={property?.cancellation_policy_text??''}/></label><label>Payment options and other policies<textarea name="policies" defaultValue={property?.extra_rules??''}/></label>
          <div className="wide stage-label" id="property-media"><b>Property media</b><span>Uploads are stored against this owner-created property draft.</span></div><label>Property cover image<input type="file" accept="image/jpeg,image/png,image/webp" data-upload-bucket="hotel-images" data-upload-output="propertyCoverUrl"/></label><label>Gallery images<input type="file" accept="image/jpeg,image/png,image/webp" multiple data-upload-bucket="hotel-images" data-upload-output="galleryUrls"/></label>
        </DirectUploadForm>
      </OnboardingSection>

      <OnboardingSection id="rooms" number="03" title="Prepare room inventory" copy={`${rooms?.length??0} room type(s) configured. Inventory remains inaccessible to booking until the property is verified and activated.`}>
        {propertyId?<><div className="readiness-list">{rooms?.map(r=><span key={r.id}><b>{r.name}</b>{r.room_type} · {r.capacity} guests · {r.currency} {r.price}</span>)}</div><DirectUploadForm action={addRoom} className="provision-form"><input type="hidden" name="propertyId" value={propertyId}/><label>Room name<input name="roomName" required/></label><label>Room type<select name="roomType" required><option value="">Choose type</option>{ROOM_TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Description<textarea name="roomDescription"/></label><label>Nightly price<input name="price" type="number" min="0" step="0.01" required/></label><label>Currency<input name="currency" defaultValue="USD" maxLength={3}/></label><label>Guest occupancy<input name="occupancy" type="number" min="1" defaultValue="2" required/></label><label>Beds<input name="beds" type="number" min="1" defaultValue="1" required/></label><label>Bathrooms<input name="bathrooms" type="number" min="0" step="0.5" defaultValue="1" required/></label><label>Available quantity<input name="quantity" type="number" min="1" defaultValue="1" required/></label><fieldset className="wide"><legend>Room amenities</legend><Checks name="roomAmenities" values={ROOM_AMENITIES}/></fieldset><label className="wide">Room image<input type="file" accept="image/jpeg,image/png,image/webp" data-upload-bucket="room-images" data-upload-output="roomImageUrl"/></label></DirectUploadForm></>:<p className="empty-state">Save the property before adding rooms.</p>}
      </OnboardingSection>

      <OnboardingSection id="discover" number="04" title="Your first Discover showcase" copy="This is not a personal introduction. Show the property, rooms, amenities, surroundings, and hospitality. It remains hidden until Ramah approves and activates it.">
        {propertyId?<><div className="readiness-list">{videos?.map(v=><span key={v.id}><b>{v.title}</b>{v.status} · {v.moderation_status}</span>)}</div><DirectUploadForm action={uploadShowcaseVideo} className="provision-form" initialMedia={videoMedia}><input type="hidden" name="propertyId" value={propertyId}/><label>Showcase title<input name="videoTitle" defaultValue="Property showcase"/></label><label>Property video<input type="file" accept="video/mp4" required data-upload-bucket="videos" data-upload-output="showcaseVideoUrl"/></label><label className="wide">What guests will experience<textarea name="videoDescription"/></label></DirectUploadForm></>:null}
      </OnboardingSection>

      <OnboardingSection id="deal" number="05" title="Configure an optional Launch Deal" copy="The duration is stored now but its countdown starts only when an authorized launch activation occurs.">
        {propertyId?<><div className="readiness-list">{deals?.map(d=><span key={d.id}><b>{d.title}</b>{d.discount_percent}% · {d.launch_duration_days} days · paused</span>)}</div><form action={saveLaunchDeal} className="provision-form"><input type="hidden" name="propertyId" value={propertyId}/><label>Deal title<input name="dealTitle" defaultValue="Launch Deal"/></label><label>Discount %<input name="discount" type="number" min="1" max="90" required/></label><label>Duration in days<input name="durationDays" type="number" min="1" max="365" required/></label><label className="wide">Description<textarea name="dealDescription"/></label><button className="button dark wide">Save paused Launch Deal</button></form><form action={submitPropertyReadiness} className="launch-submit"><input type="hidden" name="propertyId" value={propertyId}/><span><b>Ready for Ramah review?</b><small>Your property stays private after submission.</small></span><button className="button dark">Submit launch inventory</button></form></>:null}
      </OnboardingSection>
    </>:<div className="traveler-complete"><span>Traveler onboarding</span><h2>No Discover upload is required.</h2><p>Your profile and Founder membership are everything needed for this pre-launch stage.</p><a className="button dark" href="/portal/apply">Continue to membership</a></div>}
  </section>;
}

function OnboardingSection({id,number,title,copy,children}:{id:string;number:string;title:string;copy:string;children:React.ReactNode}){return <section id={id} className="onboarding-section"><header><span>{number}</span><div><h2>{title}</h2><p>{copy}</p></div></header>{children}</section>}
