import type {Metadata} from 'next';import {PublicShell} from '@/components/PublicShell';import {site} from '@/lib/site';

export const metadata:Metadata={title:{absolute:'Privacy Policy · Ramah Digital'},description:'How Ramah Digital collects, uses, stores and protects personal information.',alternates:{canonical:'/legal/privacy'},openGraph:{title:'Privacy Policy · Ramah Digital',description:'How Ramah Digital collects, uses, stores and protects personal information.',url:'/legal/privacy'},robots:{index:true,follow:true}};

const BulletList=({items}:{items:string[]})=><ul>{items.map(item=><li key={item}>{item}</li>)}</ul>;

export default function Page(){return <PublicShell><article className="legal-document privacy-document">
  <header className="legal-document-hero"><span>RAMAH DIGITAL</span><h1>PRIVACY<br/>POLICY</h1><dl><div><dt>Effective Date:</dt><dd>23 August 2026</dd></div><div><dt>Last Updated:</dt><dd>23 August 2026</dd></div><div><dt>Version:</dt><dd>1.0</dd></div></dl></header>
  <div className="legal-sections">
    <section><h2><span>1.</span> INTRODUCTION</h2><p>Welcome to Ramah Digital.</p><p>Ramah Digital respects your privacy and is committed to handling personal information responsibly, transparently, and securely.</p><p>This Privacy Policy explains how Ramah Digital collects, uses, stores, protects, and shares information when you:</p><BulletList items={["visit the Ramah Digital website;","create an account;","participate in the Founding Era;","purchase a Founder Badge;","purchase a Founding Traveler or Founding Host membership;","use the Ramah Digital application;","use the Ramah Digital platform;","communicate with Ramah Digital;","submit information as a Traveler;","submit information as a Host;","contact customer support;","interact with Ramah Digital through approved communication channels."]}/><p>For purposes of this Privacy Policy, “Ramah Digital,” “Ramah,” “we,” “us,” and “our” refer to the Ramah Digital venture and its current operator.</p><p>At the effective date of this Privacy Policy, Ramah Digital is being operated as a founder-operated venture by:</p><p><strong>David Ngang Mabior Ngang</strong></p><p>Ramah Digital is not represented as an incorporated company unless and until such registration or incorporation has actually occurred.</p></section>

    <section><h2><span>2.</span> OUR COMMITMENT TO PRIVACY</h2><p>Ramah Digital believes that personal information should be handled with:</p><BulletList items={["transparency;","integrity;","security;","accountability;","respect for individual rights."]}/><p>We do not intend to collect personal information simply because it is technically possible to collect it.</p><p>We seek to collect information that is reasonably necessary to:</p><BulletList items={["operate Ramah Digital;","provide requested services;","establish and manage accounts;","process payments;","verify users and Hosts;","administer the Founding Era;","allocate Founder Numbers;","communicate with members;","protect users;","prevent fraud;","improve our products;","comply with applicable law."]}/></section>

    <section><h2><span>3.</span> IMPORTANT INFORMATION ABOUT DATA STORAGE</h2><h3>Central European / Zurich Data Storage</h3><p>Ramah Digital&apos;s systems may use infrastructure located in Central Europe, including data-storage infrastructure in Zurich, Switzerland, for the storage and processing of personal information.</p><p>Where applicable, personal information associated with Ramah Digital accounts, Founder records, platform activity, or related services may therefore be stored on servers or cloud infrastructure located in Zurich, Switzerland / Central Europe.</p><p>Switzerland has a comprehensive legal framework governing data protection.</p><p>However, storage in Switzerland does not necessarily mean that every processing activity occurs exclusively in Switzerland.</p><p>Depending on the technology providers and services used by Ramah Digital, certain information may also be:</p><BulletList items={["processed through infrastructure located in other European countries;","transmitted through international telecommunications networks;","processed by authorized third-party service providers;","temporarily replicated for security, reliability, backup, or disaster-recovery purposes."]}/><p>Ramah Digital will take reasonable steps to ensure that international transfers and processing are handled in accordance with applicable legal requirements.</p></section>

    <section><h2><span>4.</span> WHO IS RESPONSIBLE FOR YOUR INFORMATION?</h2><p>At the date of this Privacy Policy, Ramah Digital is operated by:</p><p><strong>David Ngang Mabior Ngang</strong></p><h3>Contact Information</h3><address>Ramah Digital<br/><br/><b>Founder / Current Operator:</b><br/>David Ngang Mabior Ngang<br/><br/><b>Founder Email:</b><br/><a href="mailto:davidngangm@gmail.com">davidngangm@gmail.com</a><br/><br/><b>Support Email:</b><br/><a href="mailto:ramahdigital08@gmail.com">ramahdigital08@gmail.com</a><br/><br/><b>Telephone:</b><br/>+33753014819<br/><br/><b>Alternative Telephone:</b><br/>+211926955107<br/><br/><b>Website:</b><br/><a href={site.url}>{site.url}</a><br/><br/><b>Current Operating Country:</b><br/>Republic of South Sudan</address></section>

    <section><h2><span>5.</span> INFORMATION WE COLLECT</h2><p>The information we collect depends on how you interact with Ramah Digital.</p><p>We may collect the following categories of information.</p><h3>5.1 Account Information</h3><p>When you create an account, we may collect:</p><BulletList items={["full name;","preferred name;","username;","email address;","telephone number;","country;","city or general location;","account password or authentication information;","profile photograph;","account preferences;","membership information."]}/><p>We do not intentionally collect more information than reasonably necessary for the relevant purpose.</p></section>

    <section><h2><span>6.</span> FOUNDER INFORMATION</h2><p>If you participate in the Founding Era, we may collect information necessary to administer your Founder participation.</p><p>This may include:</p><BulletList items={["full name;","email address;","telephone number;","country;","Founder category;","membership tier;","Founder Number;","Founder Badge information;","Founder Certificate information;","membership activation date;","payment reference;","transaction information;","Founder Hall preferences;","communications relating to your membership."]}/><p>Founder Numbers may become part of your permanent Ramah Digital Founder record.</p><p>For example:</p><p>Founding Traveler #T-0042</p><p>or:</p><p>Founding Host #H-0018</p></section>

    <section><h2><span>7.</span> HOST INFORMATION</h2><p>Hosts may be required to provide additional information.</p><p>Depending on the Host service, this may include:</p><BulletList items={["Host name;","business name;","property name;","property address;","business contact information;","property photographs;","property description;","ownership or representation information;","licensing information;","registration information where applicable;","identification documents where verification is required;","banking or payout information;","tax information where required;","property facilities;","availability;","pricing;","booking information."]}/><p>Ramah may request additional information where necessary to verify a Host or property.</p></section>

    <section><h2><span>8.</span> PAYMENT INFORMATION</h2><p>When you make a payment to Ramah Digital, we may collect information necessary to verify and reconcile the transaction.</p><p>Depending on the payment method, this may include:</p><BulletList items={["payment amount;","currency;","transaction reference;","payment date;","sender name;","recipient information;","bank information necessary to identify a transfer;","mobile-money transaction information;","payment-provider reference;","receipt or proof of payment;","payment status;","refund information."]}/><h3>Payment Card Information</h3><p>Where card payments are processed through a third-party payment provider, Ramah Digital may not directly receive or store your complete card number, CVV, or other sensitive card authentication information.</p><p>Instead, such information may be processed directly by the applicable payment provider under its own security and privacy practices.</p><p>You should review the privacy policy of the applicable payment provider where appropriate.</p></section>

    <section><h2><span>9.</span> BANK TRANSFERS AND MOBILE MONEY</h2><p>During the Founding Era, Ramah Digital may accept payments through various methods, including:</p><BulletList items={["bank transfers;","mobile money;","M-Pesa;","authorized remittance services;","payment gateways;","payment links;","other approved payment methods."]}/><p>Where payment is made through a bank, mobile-money provider, or remittance provider, Ramah may receive limited transaction information necessary to identify and verify your payment.</p><p>For example, a bank transfer may provide:</p><BulletList items={["sender name;","account identifier;","transaction reference;","amount;","date;","originating institution."]}/><p>Ramah will use such information primarily for payment reconciliation, membership activation, fraud prevention, refunds, accounting, and related legitimate purposes.</p></section>

    <section><h2><span>10.</span> FOUNDER-OPERATED PAYMENT ACCOUNTS</h2><p>During the Founding Era, some payments may be received through payment accounts held by:</p><p><strong>David Ngang Mabior Ngang, the current founder and operator of Ramah Digital.</strong></p><p>Where such an arrangement is used, payment information may be available to the account holder and used for purposes including:</p><BulletList items={["confirming payment;","matching payments to Founder applications;","issuing Founder membership;","issuing Founder Numbers;","processing refunds;","maintaining transaction records;","preventing fraud;","resolving payment disputes."]}/><p>Ramah will not intentionally request payment information beyond what is reasonably necessary for the applicable transaction.</p></section>

    <section><h2><span>11.</span> TECHNICAL INFORMATION</h2><p>When you use the website or application, certain technical information may automatically be collected.</p><p>This may include:</p><BulletList items={["IP address;","browser type;","device type;","operating system;","application version;","language settings;","time zone;","referring website;","pages or screens visited;","approximate location derived from IP address;","interaction information;","error logs;","device identifiers;","security information."]}/><p>This information may be used for:</p><BulletList items={["security;","fraud prevention;","troubleshooting;","analytics;","performance monitoring;","improving the platform;","maintaining technical reliability."]}/></section>

    <section><h2><span>12.</span> LOCATION INFORMATION</h2><p>Depending on the features you use and the permissions you grant, Ramah may process location-related information.</p><p>This may include:</p><BulletList items={["country;","city;","approximate location;","property location;","travel destination;","location information voluntarily entered by you."]}/><p>Ramah will not access precise device location unless the relevant feature requires it and you provide the necessary permission.</p><p>You may be able to disable location permissions through your device settings.</p><p>Disabling location access may affect features that depend on location.</p></section>

    <section><h2><span>13.</span> COMMUNICATION INFORMATION</h2><p>When you communicate with Ramah Digital, we may retain information relating to the communication.</p><p>This may include:</p><BulletList items={["emails;","support requests;","messages;","telephone communications;","feedback;","complaints;","payment inquiries;","Founder inquiries;","technical-support communications."]}/><p>We may retain these communications to:</p><BulletList items={["respond to you;","resolve disputes;","improve customer service;","maintain records;","prevent fraud;","comply with legal obligations."]}/></section>

    <section><h2><span>14.</span> INFORMATION YOU CHOOSE TO PROVIDE</h2><p>You may voluntarily provide additional information through:</p><BulletList items={["profile information;","reviews;","property listings;","photographs;","travel preferences;","comments;","feedback;","surveys;","community participation;","social content;","Founder Hall information."]}/><p>You should avoid submitting information that you do not want Ramah to receive.</p></section>

    <section><h2><span>15.</span> HOW WE USE PERSONAL INFORMATION</h2><p>Ramah may use personal information for the following purposes.</p><h3>15.1 Account Management</h3><p>To:</p><BulletList items={["create accounts;","authenticate users;","manage profiles;","maintain memberships;","administer Founder status."]}/><h3>15.2 Founding Era Administration</h3><p>To:</p><BulletList items={["process Founder applications;","verify payments;","allocate Founder Numbers;","issue Founder Badges;","issue Founder Certificates;","manage membership tiers;","maintain Founder records;","administer Founder benefits."]}/><h3>15.3 Providing Services</h3><p>To</p><BulletList items={["operate the Ramah platform;","provide travel and hospitality services;","facilitate bookings;","connect Travelers and Hosts;","display relevant listings;","communicate service information."]}/><h3>15.4 Payments</h3><p>To:</p><BulletList items={["verify transactions;","reconcile payments;","process refunds;","detect payment fraud;","resolve payment disputes;","maintain transaction records."]}/><h3>15.5 Security</h3><p>To:</p><BulletList items={["protect accounts;","detect unauthorized access;","prevent fraud;","investigate abuse;","protect platform infrastructure;","maintain cybersecurity."]}/><h3>15.6 Customer Support</h3><p>To:</p><BulletList items={["answer questions;","investigate complaints;","resolve disputes;","provide technical support."]}/><h3>15.7 Product Development</h3><p>To:</p><BulletList items={["improve the website;","improve the application;","analyze platform performance;","develop new features;","understand user behavior;","improve user experience."]}/><h3>15.8 Communications</h3><p>To send:</p><BulletList items={["account notifications;","Founder communications;","payment confirmations;","service announcements;","security alerts;","important legal notices."]}/><p>Where required by applicable law, marketing communications will be subject to appropriate consent or opt-out mechanisms.</p></section>

    <section><h2><span>16.</span> LEGAL BASES FOR PROCESSING</h2><p>Depending on the jurisdiction applicable to you, Ramah may process personal information based on one or more lawful grounds, including:</p><BulletList items={["performance of a contract;","steps taken at your request before entering into a contract;","your consent;","legitimate interests;","compliance with legal obligations;","protection of users and platform security;","prevention of fraud."]}/><p>Where consent is the applicable legal basis, you may withdraw consent where permitted by law.</p><p>Withdrawal of consent does not necessarily affect processing that occurred lawfully before withdrawal.</p></section>
    <section><h2><span>17.</span> DATA MINIMIZATION</h2><p>Ramah intends to follow a principle of data minimization.</p><p>This means that we seek to collect information that is:</p><BulletList items={["relevant;","reasonably necessary;","proportionate to the purpose for which it is collected."]}/><p>We do not intend to collect sensitive information merely because it may be technically available.</p></section>
    <section><h2><span>18.</span> HOW WE SHARE INFORMATION</h2><p>Ramah does not intend to sell your personal information as a commercial product.</p><p>We may share personal information where reasonably necessary with:</p><h3>Payment Providers</h3><p>To process or verify payments.</p><h3>Cloud and Hosting Providers</h3><p>To store and process platform information.</p><h3>Authentication Providers</h3><p>To securely authenticate users.</p><h3>Communication Providers</h3><p>To send emails, notifications, and other communications.</p><h3>Analytics and Technology Providers</h3><p>To understand and improve platform performance.</p><h3>Travel and Hospitality Partners</h3><p>Where necessary to provide a requested service or booking.</p><h3>Professional Advisers</h3><p>Such as lawyers, accountants, auditors, or consultants where reasonably necessary.</p><h3>Authorities and Law Enforcement</h3><p>Where required by law, legal process, court order, or legitimate governmental request.</p><h3>Successor Entities</h3><p>If Ramah Digital is reorganized, incorporated, transferred, merged, acquired, or otherwise undergoes a legitimate corporate transaction, relevant information may be transferred where legally permitted.</p></section>
    <section><h2><span>19.</span> WE DO NOT SELL PERSONAL DATA</h2><p>Ramah Digital does not intend to sell personal information to third parties as a standalone commercial product.</p><p>We may, however, use information to operate the business, improve services, communicate with users, provide relevant experiences, and conduct legitimate business activities.</p><p>Where advertising or analytics technologies are introduced in the future, the applicable Privacy Policy may be updated to explain their operation.</p></section>
    <section><h2><span>20.</span> INTERNATIONAL DATA TRANSFERS</h2><p>Ramah Digital may operate across multiple countries.</p><p>As a result, personal information may be transferred across international borders.</p><p>Your information may be:</p><BulletList items={["collected in one country;","processed in another;","stored in Switzerland;","accessed by authorized service providers in another jurisdiction."]}/><p>Our current infrastructure may include Central European / Zurich-based data storage.</p><p>Where international transfers are subject to legal requirements, Ramah will seek to use appropriate safeguards required by applicable law.</p></section>
    <section><h2><span>21.</span> DATA STORAGE IN ZURICH, SWITZERLAND</h2><p>Ramah Digital places particular importance on secure infrastructure.</p><p>Personal information may be stored using cloud or database infrastructure located in:</p><p><strong>Zurich, Switzerland / Central Europe.</strong></p><p>The purpose of using such infrastructure may include:</p><BulletList items={["secure data storage;","database operation;","backup;","disaster recovery;","platform reliability;","performance;","security."]}/><p>The actual location of a particular data element may vary depending on the technology provider and service involved.</p><p>Where information is replicated for backup or disaster recovery, copies may exist in additional locations where permitted by applicable law.</p></section>
    <section><h2><span>22.</span> DATA SECURITY</h2><p>Ramah Digital takes reasonable technical and organizational measures intended to protect personal information against:</p><BulletList items={["unauthorized access;","unauthorized disclosure;","alteration;","loss;","destruction;","misuse."]}/><p>Security measures may include:</p><BulletList items={["access controls;","authentication systems;","encryption where appropriate;","secure connections;","database security;","monitoring;","backups;","role-based access;","security reviews."]}/><p>However, no internet transmission or storage system can be guaranteed to be completely secure.</p><p>Ramah therefore cannot guarantee absolute security.</p></section>
    <section><h2><span>23.</span> ACCOUNT SECURITY</h2><p>You are responsible for maintaining the security of your account.</p><p>You should:</p><BulletList items={["use a strong password;","avoid sharing credentials;","use unique credentials;","log out from shared devices;","notify Ramah of suspected unauthorized access."]}/><p>Ramah will never intentionally ask you to disclose your password through an unsolicited message.</p></section>
    <section><h2><span>24.</span> DATA RETENTION</h2><p>Ramah will retain personal information only for as long as reasonably necessary for the purposes described in this Privacy Policy, unless a longer period is required or permitted by law.</p><p>Retention periods may depend on:</p><BulletList items={["the type of information;","the purpose for which it was collected;","whether an account remains active;","legal obligations;","accounting requirements;","fraud prevention;","dispute resolution;","security requirements."]}/><p>Certain information may need to be retained after an account is closed because of legal, financial, security, or recordkeeping requirements.</p></section>
    <section><h2><span>25.</span> FOUNDER RECORD RETENTION</h2><p>Founder information may receive longer-term retention because Founder Numbers and Founder status are intended to represent historical participation in the Ramah Digital Founding Era.</p><p>For example, Ramah may retain records necessary to establish that:</p><p>Founding Traveler #T-0042</p><p>was legitimately allocated to a particular member.</p><p>Such records may include:</p><BulletList items={["Founder Number;","membership category;","activation date;","relevant transaction record;","certificate information;","Founder Badge information."]}/><p>Founder records may therefore be retained for as long as reasonably necessary to preserve the integrity of the Founding Era historical record and comply with legal obligations.</p></section>
    <section><h2><span>26.</span> COOKIES AND SIMILAR TECHNOLOGIES</h2><p>Ramah Digital may use cookies and similar technologies.</p><p>These technologies may be used to:</p><BulletList items={["keep users logged in;","remember preferences;","maintain security;","understand website usage;","measure performance;","improve user experience."]}/><p>Where required by applicable law, Ramah will provide appropriate cookie controls or consent mechanisms.</p><p>You may also control certain cookies through your browser settings.</p><p>Disabling certain cookies may affect website functionality.</p></section>
    <section><h2><span>27.</span> CHILDREN&apos;S PRIVACY</h2><p>Ramah Digital is not designed to knowingly collect personal information from children who are not legally permitted to use the applicable service.</p><p>Where a particular Ramah service has a minimum age requirement, users must meet that requirement.</p><p>If we become aware that personal information has been collected from a person who is not permitted to use the relevant service, we may take reasonable steps to delete or restrict that information where required by law.</p><p>Parents or guardians who believe a child has provided information to Ramah may contact:</p><p>ramahdigital08@gmail.com</p></section>
    <section><h2><span>28.</span> YOUR PRIVACY RIGHTS</h2><p>Depending on your country or applicable law, you may have rights concerning your personal information.</p><p>These may include the right to:</p><BulletList items={["request access to your personal information;","request correction of inaccurate information;","request deletion of certain information;","request restriction of processing;","object to certain processing;","withdraw consent where consent is the legal basis;","request a copy of certain information;","object to certain marketing communications;","raise a complaint with an applicable data-protection authority."]}/><p>These rights may be subject to legal limitations.</p></section>
    <section><h2><span>29.</span> HOW TO EXERCISE YOUR RIGHTS</h2><p>To make a privacy request, contact:</p><p>ramahdigital08@gmail.com</p><p>You may also contact:</p><p>davidngangm@gmail.com</p><p>Your request should preferably include:</p><BulletList items={["your full name;","account email;","Founder Number, if applicable;","description of your request;","information necessary to verify your identity."]}/><p>Ramah may request reasonable information to confirm that the person making the request is authorized to access or modify the relevant information.</p></section>
    <section><h2><span>30.</span> IDENTITY VERIFICATION</h2><p>For certain requests, Ramah may need to verify your identity before providing or changing information.</p><p>This is intended to prevent unauthorized persons from:</p><BulletList items={["accessing your data;","deleting your account;","changing your Founder identity;","obtaining another user's information."]}/><p>Ramah will seek to avoid collecting unnecessary identity information for this purpose.</p></section>
    <section><h2><span>31.</span> PUBLIC FOUNDER INFORMATION</h2><p>If you voluntarily consent to being displayed in the Founder Hall or another public Founder recognition feature, certain information may become publicly visible.</p><p>This may include:</p><BulletList items={["display name;","Founder Number;","Founder category;","membership tier;","country or general location;","Founder Badge;","Founder Certificate information."]}/><p>Ramah will not intentionally publish private contact information such as:</p><BulletList items={["personal email;","phone number;","payment details;","identification documents;"]}/><p>as part of ordinary Founder Hall publication.</p></section>
    <section><h2><span>32.</span> USER-CONTROLLED INFORMATION</h2><p>Where technically available, you may be able to:</p><BulletList items={["edit your profile;","update your contact information;","change preferences;","delete certain content;","control certain communications;","request account deletion."]}/><p>Certain records may need to be retained for legitimate legal, security, accounting, or historical Founder purposes.</p></section>
    <section><h2><span>33.</span> MARKETING COMMUNICATIONS</h2><p>Ramah may communicate with users about:</p><BulletList items={["new services;","Founding Era developments;","regional launches;","membership benefits;","events;","promotional opportunities;","platform announcements."]}/><p>Where required by applicable law, marketing communications will include appropriate consent and/or opt-out mechanisms.</p><p>You may request that Ramah stop sending non-essential marketing communications.</p><p>Certain transactional and legal communications cannot necessarily be opted out of, including:</p><BulletList items={["security notifications;","payment confirmations;","account notices;","changes to Terms;","important service announcements."]}/></section>
    <section><h2><span>34.</span> THIRD-PARTY LINKS</h2><p>The Ramah Digital platform may contain links to third-party websites or services.</p><p>Ramah does not control the privacy practices of those third parties.</p><p>You should review the privacy policy of any third-party service before providing personal information to it.</p></section>
    <section><h2><span>35.</span> THIRD-PARTY PAYMENT SERVICES</h2><p>Payments may be processed through third-party financial institutions and payment providers.</p><p>Those providers may independently collect and process information according to their own privacy policies.</p><p>Ramah is not responsible for privacy practices that are independently controlled by a third-party payment provider.</p></section>
    <section><h2><span>36.</span> THIRD-PARTY HOSTS AND TRAVEL PROVIDERS</h2><p>When you use Ramah to interact with a Host, property, travel provider, or other third party, certain information may need to be shared to facilitate the requested service.</p><p>The information shared will depend on the transaction.</p><p>For example, a booking may require information such as:</p><BulletList items={["name;","contact information;","booking details;","number of guests;","arrival information."]}/><p>Users should understand that third-party service providers may process information according to their own policies.</p></section>
    <section><h2><span>37.</span> DATA BREACHES AND SECURITY INCIDENTS</h2><p>If Ramah becomes aware of a security incident involving personal information, we will assess the incident and take reasonable steps to:</p><BulletList items={["contain the incident;","investigate the cause;","protect affected systems;","restore services;","comply with applicable legal obligations;","notify affected persons or authorities where legally required."]}/></section>
    <section><h2><span>38.</span> BUSINESS TRANSFERS</h2><p>If Ramah Digital is:</p><BulletList items={["incorporated;","reorganized;","merged;","acquired;","sold;","transferred;","placed under a new legal entity;"]}/><p>personal information may form part of the assets or records transferred as part of that transaction where legally permitted.</p><p>Any successor operator will be expected to handle personal information consistently with applicable privacy requirements.</p></section>
    <section><h2><span>39.</span> CHANGES TO THIS PRIVACY POLICY</h2><p>Ramah may update this Privacy Policy from time to time.</p><p>Changes may be made because of:</p><BulletList items={["new services;","new technology;","changes in data practices;","legal requirements;","regulatory developments;","security improvements;","business restructuring."]}/><p>The updated Privacy Policy will be published with a revised Last Updated date.</p><p>Where required by applicable law, Ramah will provide appropriate notice of material changes.</p></section>
    <section><h2><span>40.</span> GOVERNING LAW</h2><p>This Privacy Policy is intended to operate consistently with applicable law, including applicable privacy and data-protection requirements in the jurisdictions in which Ramah operates.</p><p>Because Ramah intends to serve users internationally, mandatory privacy rights in a user&apos;s jurisdiction may apply regardless of the governing-law provisions contained in other Ramah agreements.</p><p>Nothing in this Privacy Policy is intended to remove a legal right that cannot lawfully be removed.</p></section>
    <section><h2><span>41.</span> CONTACT US ABOUT PRIVACY</h2><p>If you have questions, concerns, complaints, or requests concerning your personal information, contact:</p><address>RAMAH DIGITAL<br/><br/><b>Founder / Current Operator:</b><br/>David Ngang Mabior Ngang<br/><br/><b>Privacy &amp; General Contact:</b><br/>ramahdigital08@gmail.com<br/><br/><b>Founder Email:</b><br/>davidngangm@gmail.com<br/><br/><b>Telephone:</b><br/>+33753014819<br/><br/><b>Alternative Telephone:</b><br/>+211926955107<br/><br/><b>Website:</b><br/><a href={site.url}>{site.url}</a></address></section>
    <section><h2><span>42.</span> PRIVACY ACKNOWLEDGEMENT</h2><p>By creating an account, using Ramah Digital, joining the Founding Era, purchasing a Founder Badge, purchasing a membership, submitting information, or otherwise using Ramah Digital services, you acknowledge that you have had an opportunity to review this Privacy Policy.</p><p>You understand that:</p><BulletList items={["Ramah collects information necessary to operate its services;","Ramah may process account, payment, technical, communication, and membership information;","Founder information may be retained as part of the historical Founder record;","certain information may be shared with authorized service providers;","payment providers may independently process payment information;","Ramah's infrastructure may include data storage in Zurich, Switzerland / Central Europe;","information may be processed across international borders;","Ramah takes reasonable measures to protect personal information;","no internet-based system can guarantee absolute security;","you may have privacy rights depending on your jurisdiction;","you may contact Ramah regarding privacy matters at ramahdigital08@gmail.com."]}/></section>
    <section><h2><span>43.</span> FINAL PRIVACY STATEMENT</h2><p>Ramah Digital is being built with the principle that trust is infrastructure.</p><p>Your personal information is not merely technical data. It is information entrusted to Ramah in order to participate in a digital travel and hospitality ecosystem.</p><p>We therefore intend to treat personal information with care, use it for legitimate purposes, limit unnecessary collection, protect it through reasonable security measures, and provide transparency about how it is handled.</p><p>Where our infrastructure uses Central European data storage, including Zurich, Switzerland, we will continue working to maintain appropriate technical and organizational safeguards as Ramah Digital grows internationally.</p><p>Your data. Your privacy. Your trust.</p><p>RAMAH DIGITAL</p><p>Your Home. Your World. Your Journey.</p><p>Privacy Policy Version: 1.0<br/>Effective Date: 23 August 2026<br/>Last Updated: 23 August 2026</p></section>
  </div>
</article></PublicShell>}
