import Image from 'next/image';import Link from 'next/link';import {FounderBadge} from '@/components/FounderBadge';import {createClient} from '@/lib/supabase/server';import {tierName} from '@/lib/memberships';import {savePublication} from './actions';
import {ApplicationSubmittedState} from '@/components/ApplicationSubmittedState';
type Benefit={code:string;title:string;availability:'available_now'|'upcoming'|'unavailable'};
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const q=await searchParams,sb=await createClient();const {data:{user}}=await sb.auth.getUser();
 const [{data:portal},{data:applications},{data:profile}]=await Promise.all([sb.rpc('get_founder_portal'),sb.from('founding_applications').select('id,application_type,status,requested_tier_code,submitted_at,activated_at').order('submitted_at',{ascending:false}).limit(1),user?sb.from('profiles').select('full_name,business_name,avatar_url,country,bio,role').eq('id',user.id).maybeSingle():Promise.resolve({data:null})]);
 const app=applications?.[0],identity=portal?.founderIdentity,membership=portal?.membership,credential=portal?.credential;const founderLabel=identity?.founderType==='host'?'Founding Host':'Founding Traveler';const displayName=profile?.full_name??profile?.business_name??user?.user_metadata?.full_name??'Ramah Founder';const active=membership?.status==='active';const certificateReady=credential?.verification_status==='active';
 if(app&&!identity?.founderStatus)return <ApplicationSubmittedState displayName={displayName} application={app} profileComplete={Boolean(profile?.full_name)} identity={identity} badges={portal?.badges} certificateReady={certificateReady} hallEligible={Boolean(portal?.publicProfile)} notice={q.notice}/>;
 return <><section className="portal-welcome"><span className="eyebrow">Founder Headquarters</span><h1>Welcome, {String(displayName).split(' ')[0]}.</h1><p>{identity?.founderStatus?'Your permanent place in Ramah history is confirmed.':app?'Your application is moving through the founding journey.':'Your Ramah account is ready. Choose a membership when you are ready.'}</p>{q.notice&&<div className="notice" role="status">{q.notice}</div>}{q.error&&<div className="form-error" role="alert">{q.error}</div>}</section>
 <section className="status-ribbon"><div><span>Founder status</span><b>{identity?.founderStatus?founderLabel:'Pending'}</b></div><div><span>Founder identifier</span><b>{identity?.founderNumber??'Assigned at activation'}</b></div><div><span>Membership tier</span><b>{tierName(membership?.tierCode??app?.requested_tier_code)}</b></div><div><span>Membership status</span><b>{membership?.status??app?.status??'Not active'}</b></div></section>
 {!app&&<section className="portal-next"><div><span className="eyebrow">Your next step</span><h2>Choose your membership.</h2><p>The application is attached to the same account used by the Ramah app.</p></div><Link className="button dark" href="/portal/apply">View memberships</Link></section>}
 {identity?.founderStatus&&<><section className="headquarters-grid"><article className="founder-profile-card">{profile?.avatar_url?<Image src={profile.avatar_url} alt={`${displayName} profile`} width={112} height={112}/>:<span className="profile-monogram">{String(displayName).charAt(0)}</span>}<span className="eyebrow">Lifetime recognition</span><h2>{displayName}</h2><p>{founderLabel} · {tierName(membership?.tierCode)}</p></article><FounderBadge founderNumber={identity.founderNumber} founderType={identity.founderType} tierCode={membership?.tierCode}/></section>
 <section className="founder-progress" aria-label="Founder journey"><p>{active?'✓':'○'} Membership Active</p><p>✓ Founder Identity Confirmed</p><p>✓ Founder Number Assigned</p><p>{portal?.badges?.length?'✓':'○'} Founder Badge Activated</p><p>{certificateReady?'✓':'○'} Founder Certificate Issued</p><p>{portal?.publicProfile?.publication_consent?'✓':'○'} Founder Hall Eligibility</p></section>
 <section className="legacy-cards"><article><span className="eyebrow">Founder Certificate</span><h2>{certificateReady?'Ready for the wall.':'Being prepared.'}</h2><p>{certificateReady?'Your signed Ramah Digital certificate is ready to download or print for your home, office, or hotel reception.':'Your certificate becomes available when the official credential is issued.'}</p>{certificateReady&&<Link className="button dark" href="/portal/certificate">View and download certificate</Link>}</article><article><span className="eyebrow">Founder Hall</span><h2>{portal?.publicProfile?.publication_consent?'Consent recorded':'Private by default'}</h2><p>You control whether your name, country, image, story, or property enters the historical public record.</p></article></section></>}
 {app&&!identity?.founderStatus&&<section className="portal-next"><div><span className="eyebrow">Application progress</span><h2>Your record is being reviewed.</h2><p>{tierName(app.requested_tier_code)} · {app.application_type}. A Founder Number is never reserved before activation.</p></div></section>}
 <section className="benefits"><div><span className="eyebrow">Founder privileges</span><h2>Clear about what exists.</h2><p>Founder recognition and today’s privileges are separated from products that arrive with the Ramah platform launch.</p></div><BenefitGroup title="Active Today" items={(portal?.benefits??[]).filter((b:Benefit)=>b.availability==='available_now')}/><BenefitGroup title="Coming With Launch" items={(portal?.benefits??[]).filter((b:Benefit)=>b.availability==='upcoming')}/></section>
 <section className="account-record"><div><span className="eyebrow light">Your Ramah record</span><h2>One identity.<br/>Every chapter.</h2><p>This is the same account that carries into the Ramah app. Your membership may evolve; your Founder Identifier remains permanent.</p></div><dl><div><dt>Account name</dt><dd>{displayName}</dd></div><div><dt>Ramah email</dt><dd>{user?.email??'Private'}</dd></div><div><dt>Country</dt><dd>{profile?.country??'Not added'}</dd></div><div><dt>Founder identity</dt><dd>{identity?.founderStatus?`${founderLabel} · ${identity.founderNumber}`:'Pending activation'}</dd></div><div><dt>Membership</dt><dd>{tierName(membership?.tierCode??app?.requested_tier_code)}</dd></div><div><dt>Credential</dt><dd>{credential?.credential_number??'Issued after activation'}</dd></div></dl></section>
 {portal?.publicProfile&&<section className="privacy-form"><div><span className="eyebrow">Founder Hall & privacy</span><h2>You decide what enters the public record.</h2><p>Private contact and payment information are never included.</p></div><form action={savePublication}><label><input type="checkbox" name="consent" defaultChecked={portal.publicProfile.publication_consent}/> I consent to publication review</label><label>Display name<select name="displayNameMode" defaultValue={portal.publicProfile.display_name_mode}><option value="first_name">First name</option><option value="full_name">Full name</option><option value="initials">Initials</option><option value="property_name">Business name</option><option value="custom">Custom</option></select></label><label>Custom display name<input name="customName" defaultValue={portal.publicProfile.custom_display_name??''}/></label><label>Founder story<textarea name="story" maxLength={1200} defaultValue={portal.publicProfile.founder_story??''}/></label><div className="checks"><label><input type="checkbox" name="showAvatar" defaultChecked={portal.publicProfile.show_avatar}/> Show photo</label><label><input type="checkbox" name="showCountry" defaultChecked={portal.publicProfile.show_country}/> Show country</label><label><input type="checkbox" name="showCity" defaultChecked={portal.publicProfile.show_city}/> Show city</label><label><input type="checkbox" name="showProperty" defaultChecked={portal.publicProfile.show_property}/> Show business</label><label><input type="checkbox" name="discoverable" defaultChecked={portal.publicProfile.discoverable}/> Discoverable in Hall</label></div><button className="button dark">Save Founder Hall preferences</button></form></section>}</>;
}
function BenefitGroup({title,items}:{title:string;items:Benefit[]}){return <div className="benefit-group"><h3>{title}</h3>{items.length?items.map(item=><p key={item.code}>✓ {item.title}</p>):<p className="muted">Benefits appear here after activation.</p>}</div>}
