import type {Metadata} from 'next';import {PublicShell} from '@/components/PublicShell';import {site} from '@/lib/site';

export const metadata:Metadata={title:{absolute:'Founding Era Terms & Conditions · Ramah'},description:'Terms governing participation in the Ramah Digital Founding Era.',alternates:{canonical:'/legal/terms'},openGraph:{title:'Founding Era Terms & Conditions · Ramah',description:'Terms governing participation in the Ramah Digital Founding Era.',url:'/legal/terms'},robots:{index:true,follow:true}};

const BulletList=({items}:{items:string[]})=><ul>{items.map(item=><li key={item}>{item}</li>)}</ul>;

export default function Page(){return <PublicShell><article className="legal-document">
  <header className="legal-document-hero"><span>RAMAH DIGITAL</span><h1>FOUNDING ERA<br/>TERMS &amp; CONDITIONS</h1><dl><div><dt>Effective Date:</dt><dd>23 August 2026</dd></div><div><dt>Last Updated:</dt><dd>23 August 2026</dd></div><div><dt>Version:</dt><dd>1.0</dd></div></dl></header>

  <section className="legal-notice"><h2>IMPORTANT NOTICE</h2><p>These Founding Era Terms &amp; Conditions (&quot;Terms&quot;) govern participation in the <strong>Ramah Digital Founding Era</strong> (&quot;Founding Era&quot;), including the purchase or activation of a Founding Traveler or Founding Host membership, purchase of a Founder Badge, allocation of a Founder Number, access to applicable Founder benefits, and use of the associated Ramah Digital website, application, dashboard, and services.</p><p>At the date these Terms take effect, Ramah Digital is being developed and operated as a <strong>founder-operated travel and hospitality technology venture</strong> under the Ramah Digital brand by:</p><p><strong>David Ngang Mabior Ngang</strong></p><p>Ramah Digital is <strong>not represented in these Terms as an incorporated company or registered company unless and until such registration has actually occurred</strong>.</p><p>The Founding Era is an early, pre-launch membership and recognition program intended to establish Ramah Digital&apos;s initial community of travelers and hospitality partners before and during the phased launch of the platform.</p><p>Participation in the Founding Era does not give a member ownership, shares, securities, investment rights, voting rights, profit participation, or any other ownership interest in Ramah Digital or in any company that may subsequently operate, own, or acquire the Ramah Digital platform.</p><p>A Founder is a <strong>member and early participant in the Ramah Digital ecosystem, not an investor in Ramah Digital</strong>.</p><p>By selecting a membership, purchasing a Founder Badge, submitting an application, making a payment, activating a membership, checking an acceptance box, or otherwise participating in the Founding Era, you confirm that you have read, understood, and agreed to these Terms.</p><p>If you do not agree to these Terms, you should not purchase, activate, or participate in the Founding Era.</p></section>

  <div className="legal-sections">
    <section><h2><span>1.</span> ABOUT RAMAH DIGITAL</h2><p>Ramah Digital is a travel and hospitality technology venture being developed to connect travelers, hospitality businesses, properties, destinations, and related travel services through digital technology.</p><p>The long-term vision of Ramah Digital is to provide travelers and hospitality businesses with a connected digital ecosystem for discovering, planning, booking, managing, and participating in travel and hospitality opportunities.</p><p>The Ramah Digital brand, website, application, platform, content, systems, and associated services are currently operated by:</p><address><b>Current Operator:</b> David Ngang Mabior Ngang<br/><b>Trading/Operating Name:</b> Ramah Digital<br/><b>Country of Operation:</b> Republic of South Sudan<br/><b>Official Email:</b> <a href="mailto:davidngangm@gmail.com">davidngangm@gmail.com</a><br/><b>Support Email:</b> <a href="mailto:ramahdigital08@gmail.com">ramahdigital08@gmail.com</a><br/><b>Telephone:</b> +33753014819<br/><b>Alternative Telephone:</b> +211926955107<br/><b>Website:</b> <a href={site.url}>{site.url}</a></address><p>Where these Terms use the words <strong>&quot;Ramah Digital,&quot; &quot;Ramah,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our,&quot;</strong> they refer to the Ramah Digital venture and, where legally applicable, to David Ngang Mabior Ngang as the current operator of that venture.</p><p>Ramah Digital may subsequently be incorporated, registered, reorganized, transferred, or operated through one or more legal entities.</p><p>Nothing in these Terms represents that such future entity already exists.</p><p>If the Ramah Digital venture is subsequently transferred to or operated by a legally incorporated or registered entity, that entity may become the contracting operator of the platform subject to applicable law and appropriate notice.</p></section>

    <section><h2><span>2.</span> PURPOSE OF THE FOUNDING ERA</h2><p>The Founding Era is Ramah Digital&apos;s limited early-member program established before and during the initial commercial development and phased launch of the Ramah Digital platform.</p><p>The Founding Era is designed to:</p><BulletList items={["establish Ramah Digital's first community of travelers;","establish an initial community of hospitality businesses and Hosts;","recognize early supporters of the platform;","provide eligible members with Founder recognition;","establish sequential Founder Numbers;","provide applicable early-member benefits;","provide Ramah with an initial community with which to develop and launch its platform;","create an identifiable historical record of the people and Hosts who joined Ramah Digital during its Founding Era."]}/><p>The Founding Era is therefore intended to represent a <strong>limited period of early participation in the development and expansion of Ramah Digital</strong>.</p><p>The Founding Era does not represent a guarantee that the entire Ramah Digital platform will be operational in every country at the time a member joins.</p></section>

    <section><h2><span>3.</span> FOUNDING ERA GLOBAL SCOPE</h2><p>The Ramah Digital Founding Era is intended to have a <strong>global reach for Travelers</strong>.</p><p>A person who is eligible to participate as a Founding Traveler may participate from countries and regions around the world, subject to applicable law, payment availability, verification requirements, sanctions restrictions, technical availability, and other applicable limitations.</p><h3>Founding Travelers</h3><p>The Founding Traveler program is <strong>global</strong>.</p><p>This means that Ramah may accept eligible Travelers from different countries and regions during the Founding Era even where Ramah Digital has not yet commercially launched its full range of services in that Traveler&apos;s country.</p><p>However, participation in the global Founding Era does <strong>not</strong> mean that every Ramah Digital service is immediately available in every country.</p><p>A Founder may join before Ramah launches in their country or region.</p><p>Where Ramah has not yet launched in the Founder&apos;s region, applicable benefits may remain pending until the relevant Ramah services become available in that region.</p></section>

    <section><h2><span>4.</span> FOUNDING HOST GEOGRAPHIC SCOPE</h2><p>The Founding Host program is initially intended for eligible hospitality businesses and Hosts located within the <strong>Global South</strong>, subject to Ramah&apos;s eligibility, verification, operational, legal, and market requirements.</p><p>For purposes of the Founding Era, <strong>Global South</strong> generally refers to countries and markets across Africa, Latin America and the Caribbean, South Asia, Southeast Asia, the Middle East, and other developing or emerging markets traditionally associated with the Global South.</p><p>Ramah may determine from time to time which countries, territories, cities, or markets qualify for Founding Host participation.</p><p>The Global South scope is intended to align the initial Host community with Ramah Digital&apos;s strategic focus on emerging and developing travel and hospitality markets.</p><p>Ramah may expand, modify, or refine Host eligibility as the platform develops.</p><p>Participation as a Founding Host does not guarantee that Ramah will immediately launch commercial operations in the Host&apos;s particular country or city.</p></section>

    <section><h2><span>5.</span> FOUNDING ERA ALLOCATION</h2><p>The initial and maximum published Founding Era allocation consists of:</p><h3>Travelers</h3><p><strong>700 Founding Traveler positions</strong></p><h3>Hosts</h3><p><strong>300 Founding Host positions</strong></p><p>These separate allocations preserve the limited nature and historical significance of the Founding Era.</p><p>Ramah may close a category when its allocation has been reached and may close, suspend, interrupt or extend the application period where reasonably necessary because of:</p><BulletList items={["legal or regulatory requirements;","payment limitations;","security or technical circumstances;","operational requirements;","fraud prevention;","market conditions;","circumstances beyond reasonable control."]}/><p><strong>An operational extension, interruption or suspension changes timing only and does not by itself increase the published allocation of 700 Founding Travelers and 300 Founding Hosts.</strong> Any legally required material change will be communicated through appropriate official Ramah channels where reasonably practicable.</p></section>

    <section><h2><span>6.</span> FOUNDING ERA MEMBERSHIP TYPES</h2><h3>TRAVELERS</h3><div className="legal-tier"><h4>Explore</h4><strong>US$29 one-time payment</strong><p>The Explore membership is an entry-level Founding Traveler membership intended for Travelers who wish to participate in the Founding Era and receive the benefits expressly associated with the Explore tier.</p></div><div className="legal-tier"><h4>Voyager</h4><strong>US$49 one-time payment</strong><p>The Voyager membership is a higher Founding Traveler membership intended for Travelers seeking the additional benefits expressly associated with the Voyager tier.</p></div><h3>HOSTS</h3><div className="legal-tier"><h4>Community Host</h4><strong>Free</strong><p>Community Host is a free entry-level Host membership.</p></div><div className="legal-tier"><h4>Founding Host</h4><strong>US$29 one-time payment</strong></div><div className="legal-tier"><h4>Signature Host</h4><strong>US$59 one-time payment</strong></div><div className="legal-tier"><h4>Prestige Host</h4><strong>US$99 one-time payment</strong></div><div className="legal-tier"><h4>Legacy Host</h4><strong>US$199 one-time payment</strong></div><p>The applicable benefits for each tier are those expressly communicated by Ramah through the Founding Era membership materials, website, application, dashboard, or other official communications.</p><p>Prices are stated in United States dollars unless the applicable payment instructions expressly state another currency.</p><p>Where payment is made in another currency, the amount may vary because of:</p><BulletList items={["exchange rates;","bank conversion;","mobile-money conversion;","payment-provider conversion;","remittance-provider conversion;","transaction charges."]}/><p>Applicable taxes, payment-provider charges, currency-conversion charges, transfer charges, or other legally required charges will be disclosed where reasonably applicable.</p></section>

    <section><h2><span>7.</span> FOUNDER BADGE</h2><p>Ramah Digital may make a <strong>Founder Badge</strong> available for purchase or activation before or independently of a full Founding Era membership.</p><p>The Founder Badge is intended to provide a visible digital symbol of support and association with the Ramah Digital Founding Era.</p><p>A person may purchase or receive a Founder Badge before completing a Founding Traveler or Founding Host membership, where Ramah makes such an option available.</p><p>However, unless expressly stated otherwise:</p><p><strong>Purchasing a Founder Badge alone does not automatically create a Founder Number, Founding Traveler membership, Founding Host membership, Host account, Traveler membership, ownership interest, investment interest, or entitlement to every Founding Era benefit.</strong></p><p>Founder Badge ownership and Founding Era membership are separate concepts unless the applicable offer expressly combines them.</p><p>Where a Founder Badge is bundled with a membership, the applicable offer will state the relationship between the Badge and the membership.</p><p>Ramah may provide different Founder Badge designs, levels, digital formats, verification systems, or other forms of recognition over time.</p><p>A Founder Badge is a recognition item and does not represent:</p><BulletList items={["shares;","securities;","equity;","an investment;","financial ownership;","a guaranteed financial return;","a monetary asset;","a promise of appreciation."]}/></section>

    <section><h2><span>8.</span> MEMBERSHIP IS NOT AN INVESTMENT</h2><p>A Founding Era membership is a membership product and recognition program.</p><p>Purchasing a Founding Era membership does <strong>not</strong>:</p><BulletList items={["give you shares in Ramah Digital;","give you shares in any future Ramah company;","give you voting rights;","give you ownership of Ramah Digital;","create a partnership;","create a joint venture;","create an agency relationship;","create a creditor relationship;","create a deposit;","constitute a loan;","constitute a securities offering;","entitle you to dividends;","entitle you to company profits;","entitle you to a percentage of Ramah Digital revenue;","guarantee financial returns;","guarantee appreciation in the value of your membership;","guarantee employment;","guarantee bookings;","guarantee accommodation;","guarantee travel savings;","guarantee future monetary benefits."]}/><p>A Founder is a <strong>member of the Ramah Digital Founding Era, not an investor in Ramah Digital</strong>.</p><p>Any future investment opportunity, share offering, equity arrangement, crowdfunding arrangement, or other investment product would be separate and would require its own documentation and applicable legal compliance.</p></section>

    <section><h2><span>9.</span> FOUNDER STATUS</h2><p>An eligible participant who successfully completes the applicable Founding Era activation process may receive Founder recognition.</p><p>Depending on the applicable membership, Founder recognition may include:</p><BulletList items={["Founder Number;","Founder Badge;","Founder Certificate;","Founder Dashboard recognition;","Founder Hall eligibility;","applicable Founding Era benefits;","other benefits expressly stated by Ramah."]}/><p>Founder status is separate from the member&apos;s commercial membership tier.</p><p>For example:</p><p><strong>Founding Traveler #T-0042</strong><br/><strong>Voyager</strong></p><p>or:</p><p><strong>Founding Host #H-0018</strong><br/><strong>Prestige Host</strong></p><p>Changing a membership tier does not automatically change an already allocated Founder Number.</p></section>

    <section><h2><span>10.</span> FOUNDER NUMBERS</h2><p>Founder Numbers are allocated sequentially according to the applicable Founder category and available allocation.</p><p>Traveler Founder Numbers use the format:</p><p><strong>T-0001 to T-0700</strong></p><p>Host Founder Numbers use the format:</p><p><strong>H-0001 to H-0300</strong></p><p>A Founder Number is intended to be a permanent identifier associated with the Founder account to which it was legitimately allocated.</p><p>Founder Numbers:</p><BulletList items={["cannot ordinarily be selected by the customer;","cannot ordinarily be transferred;","cannot be sold;","cannot be assigned to another person;","cannot be duplicated;","cannot be reserved outside the official allocation process;","cannot be obtained through manipulation of the platform."]}/><p>Ramah may revoke or invalidate a Founder Number where it was obtained through:</p><BulletList items={["fraud;","payment fraud;","unauthorized payment;","account compromise;","identity fraud;","multiple-account abuse;","manipulation of Founder allocation;","chargeback abuse;","material violation of these Terms."]}/><p>Where a Founder Number has been legitimately allocated and the Founder remains compliant with these Terms, Ramah will not arbitrarily reassign that Founder Number to another person.</p></section>

    <section><h2><span>11.</span> REGIONAL LAUNCH AND AVAILABILITY OF BENEFITS</h2><p>The Founding Era is global for Travelers and initially focused on the Global South for Hosts.</p><p>However, <strong>Ramah Digital may not launch in every country, city, territory, or region at the same time.</strong></p><p>A person may therefore become a Founder before Ramah Digital becomes commercially operational in that person&apos;s region.</p><p>This is an important characteristic of the Founding Era.</p><h3>Example</h3><p>A Traveler in Country A may join the Founding Era in 2026 even though Ramah Digital has not yet launched its full travel services in Country A.</p><p>That person may receive their Founder Number and applicable Founding Era recognition.</p><p>However, certain platform benefits may remain unavailable until Ramah Digital launches the applicable services in Country A.</p><p>When Ramah Digital subsequently launches in that region, the Founder may become eligible to enjoy the applicable privileges and benefits associated with their membership, subject to:</p><BulletList items={["the membership tier;","the services actually launched;","applicable local law;","availability;","eligibility requirements;","any applicable service-specific terms."]}/><h3>No Immediate Regional Launch Guarantee</h3><p>Joining the Founding Era does not</p></section>
  </div>
</article></PublicShell>}
