import Image from 'next/image';import Link from 'next/link';import {PublicShell} from '@/components/PublicShell';import {CampaignPanel} from '@/components/CampaignPanel';import {SocialContactSection} from '@/components/SocialContactSection';import {getFounders} from '@/lib/supabase/queries';import {FoundingCtaLink} from '@/components/FoundingCtaLink';import {site} from '@/lib/site';
const faq=[['What makes founder status permanent?','Your founder identity records that you joined during Ramah’s first chapter. Membership benefits may renew or expire; verified founder recognition remains.'],['Can I use the same account in the Ramah App?','Yes. The website and app use the same Ramah Digital Supabase Auth identity.'],['Are smaller properties treated differently?','No. Host offers support different operational needs; they do not rank the worth of a property or its hospitality.']];
export default async function Home(){const founders=await getFounders(3);const org={"@context":"https://schema.org","@type":"Organization","name":"Ramah Digital","url":site.url,"description":"A founder-operated travel and hospitality venture connecting travelers and accommodation partners across Africa and the Global South."};return <PublicShell><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(org)}}/><section className="hero"><Image src="/images/founding-hero.png" fill priority sizes="100vw" alt="Travelers being welcomed to a highland lodge at sunrise"/><div className="hero-shade"/><div className="hero-copy"><span className="eyebrow light">Official Ramah Digital Founding Era website · Pre-launch</span><h1>History Has<br/><em>1,000 Places.</em></h1><p>Pre-register now and be ready for the official opening on 30 August 2026. Account creation does not reserve or assign a Founder Number.</p><div className="actions"><FoundingCtaLink className="button light" kind="traveler" tier="explore"/><FoundingCtaLink className="button outline-light" kind="host" tier="community"/></div></div><a className="scroll-cue" href="#record">Discover the founding record <span>↓</span></a></section><div id="record"><CampaignPanel/></div>
<section className="editorial"><div className="editorial-number">01</div><div><span className="eyebrow">Every great institution has a beginning</span><h2>A moment that can never be repeated.</h2></div><div><p>Ramah exists to bring travelers and hosts closer to the places, people and stories that make a journey matter.</p><p>Founders do more than arrive early. They help set the tone for what follows—and carry that history with them.</p><Link className="arrow-link" href="/story">Read the founding story <span>↗</span></Link></div></section>
<section className="split-invitation"><article className="traveler"><span className="eyebrow light">Founding Traveler</span><h2>Travel with a place in the record.</h2><p>A permanent founder number, digital badge, verifiable credential, certificate and an early voice in the Ramah community.</p><Link className="button light" href="/founding-travelers">Discover the traveler invitation</Link></article><article className="host"><span className="eyebrow">Founding Host</span><h2>Hospitality belongs in history too.</h2><p>For hotels, guesthouses, lodges, villas and serviced stays—each supported according to its own operational needs.</p><Link className="button dark" href="/founding-hosts">Discover the host invitation</Link></article></section>
<section className="identity-section"><div><span className="eyebrow">Identity and membership</span><h2>One is remembered.<br/>One is renewed.</h2></div><div className="identity-lines"><div><b>Permanent</b><h3>Founding identity</h3><p>Your verified place in Ramah’s first chapter does not expire.</p></div><div><b>Renewable</b><h3>Circle membership</h3><p>Benefits and access depend on your current membership status.</p></div></div></section>
<section className="image-story"><Image src="/images/founding-community.png" fill sizes="100vw" alt="Travelers and African hospitality hosts gathered in a warm courtyard"/><div><span className="eyebrow light">A community before a platform</span><blockquote>“The first names in a century-long story.”</blockquote></div></section>
<section className="hall-preview"><div className="section-heading"><div><span className="eyebrow">Hall of Founders</span><h2>The record begins here.</h2></div><Link className="arrow-link" href="/founders">Explore the Hall <span>↗</span></Link></div>{founders.length?<div className="founder-list">{founders.map(f=><Link href={`/founders/${f.public_slug}`} key={f.public_slug}><span>{f.founder_number}</span><h3>{f.display_name}</h3><p>{[f.city,f.country].filter(Boolean).join(', ')}</p></Link>)}</div>:<div className="empty-state"><b>The first profiles will appear after activation and consent.</b><p>No founder is shown until their identity is issued and their publication is approved.</p></div>}</section>
<section className="journey"><span className="eyebrow">How it works</span><h2>From account to founder identity.</h2><ol>{['Create your Ramah account','Verify your email','Choose your founding path','Submit your application','Ramah reviews your application','Receive Founder approval','Receive your founder number','Enter your portal and the app'].map((x,i)=><li key={x}><span>{String(i+1).padStart(2,'0')}</span>{x}</li>)}</ol><Link className="button dark" href="/how-it-works">See the complete journey</Link></section>
<section className="credential"><div><span className="eyebrow">Founder credentials</span><h2>A mark that can be verified.</h2><p>Your founder number, permanent badge and public verification route connect the physical certificate to Ramah’s live record.</p></div><div className="certificate"><span>RAMAH · FOUNDING ERA</span><b>Founding Traveler</b><strong>T-0001</strong><small>Example format · not an issued founder</small></div></section>
<section className="referral"><span className="eyebrow light">The invitation travels</span><h2>Bring someone who should be remembered too.</h2><p>Verified founders receive a personal referral code. Eligible referrals are recorded only after activation—never before.</p></section>
<section className="faq"><div><span className="eyebrow">Questions, answered plainly</span><h2>Before you take your place.</h2><Link className="arrow-link" href="/faq">Read all questions <span>↗</span></Link></div><div>{faq.map(([q,a])=><details key={q}><summary>{q}<span>＋</span></summary><p>{a}</p></details>)}</div></section>
<SocialContactSection/><section className="final-cta"><span className="eyebrow light">Pre-registration is available</span><h2>Be ready for<br/><em>the Founding Era.</em></h2><p>Founder places are governed by the official opening, review and allocation process.</p><div className="actions"><FoundingCtaLink className="button light" kind="traveler" tier="explore"/><FoundingCtaLink className="button outline-light" kind="host" tier="community"/></div></section></PublicShell>}
